### ISSUE TITLE
Missing dSym for release 8.3

### ISSUE THREAD

**Issue by laursen86** [NativeScript/ios#183]
There is no dSym file attached to the release 8.3. The latest is for 8.2.0 - 8.2.1.

**Comment by rigor789** [comment]
dSYMS should now be included in the NativeScript.xcframework itself copied to `platforms/ios/internal/NativeScript.xcframework` - not sure if that's enough, perhaps we could still figure out how to generate a zip file of these to be easily attachable to error trackers like Sentry/Firebase Crashlytics.

![image](https://user-images.githubusercontent.com/879060/202875037-e7ecfd0c-a32a-49f5-8ec1-b7a5ac63a77f.png)
