### ISSUE TITLE
Xcode 14.3 

### ISSUE THREAD

**Issue by HoncoTech** [NativeScript/ios#207]
Xcode version 14.3 (14E222b) + iOS 16.4 + MacOSX Ventura 13.3 , I am not able to build the nativescript project. The tns-ios version is 6.5.3. Getting below error-

error: Build input file cannot be found: '/Users/xxxxxxxxx/yyyyyy/zzzzzzz/platforms/ios/build/Debug-iphonesimulator/metadata-x86_64.bin'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'XXXXXXXX' from project 'YYYYYYYY')

**Comment by rigor789** [comment]
Update to at least 6.5.4 (but preferably 8.5.1 if able to).

**Comment by HoncoTech** [comment]
Updating to 6.5.6 worked for me. Thanks for help. Also can you suggest solution for already reported issue-
https://github.com/NativeScript/Nativescript/issues/10123
