### ISSUE TITLE
iOS Crash when trying to use Sqlite via workers on iOS platform 8.5.0+

### ISSUE THREAD

**Issue by shiv19** [NativeScript/ios#208]
When we try to create a multithreaded instance of the nativescript-sqlite plugin on iOS using @nativescript/ios 8.5.0+ the app crashes with the error: `FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place`

Github repo with a sample project to recreate the issue with explanation of the issue:
https://github.com/markoImake/sqlite-issue

@rigor789, I can share the plugin with you on slack as this is a paid plugin.

**Comment by alexander-mai** [comment]
This is not a problem with Sqlite. It is a worker problem.
Creating a Worker ```new Worker(...);``` results in a crashed app.
With the new Versions of ```@nativescript/ios``` (tested with ```8.5.2-alpha.3``` and ```8.5.2-next.2023-05-11-4953202683) the problem is fixed and workers are working well.
